[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mtglabels"
version = "0.0.19"
description = "Magic: the Gathering Printable Set Label Generator"
authors = ["Evgenii Vasilenko <gmrnsk@gmail.com>"]

dependencies = [
    "jinja2==3.1.2",
    "requests==2.31.0",
    "cairosvg==2.7.1",
    "markupsafe==2.1.3",
    "pypdf2==3.0.1",
]

[project.optional-dependencies]
dev = [
    "black==23.11.0",
]
