---
name: Build & Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/dependabot.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade setuptools and wheel
        run: |
          pip install \
            --no-cache-dir \
            --disable-pip-version-check \
            --upgrade \
            pip \
            setuptools \
            wheel

      - name: Install poetry
        run: |
          pip install \
            --no-cache-dir \
            --disable-pip-version-check \
            poetry

      - name: Install Python modules
        env:
          POETRY_VIRTUALENVS_CREATE: false
        run: |
          poetry install --no-cache --no-root --without dev
          pip list

      - name: Test generator.py
        run: |
          python mtglabels/generator.py --labels-per-sheet 30 --output-dir /tmp ice
